export const lulus = [
  {
    id: 4,
    nome: 'Sueli',
    foto: '/fotos/Sueli.jpg',
    birthdate: '1985-04-09 00:00:00',
    iconesigno: 'noto-v1:aries',
    chavePix: '31511703822',
    tipoChavePix: 'cpf',
    apelido: null,
    sobrenome: ' Corrêa de Oliveira',
    instagram: 'suelli_correaa',
    images: null,
    picture_url: null,
  },
  {
    id: 6,
    nome: 'Carolina',
    foto: '/fotos/CarolMaita.jpg',
    birthdate: '2000-05-28 00:00:00',
    iconesigno: 'noto-v1:gemini',
    chavePix: '28375340804',
    tipoChavePix: 'cpf',
    apelido: 'Carol Maita',
    sobrenome: ' Maita',
    instagram: 'carolmaita',
    images: '9a56cefc-cfc3-4c8c-ab76-f3bff0286715',
    picture_url: null,
  },
  {
    id: 29,
    nome: 'Não Participa da Vaquinha',
    foto: null,
    birthdate: null,
    iconesigno: null,
    chavePix: null,
    tipoChavePix: null,
    apelido: null,
    sobrenome: '',
    instagram: null,
    images: null,
    picture_url: null,
  },
  {
    id: 27,
    nome: 'Vládia Maria',
    foto: '/fotos/Vladia.jpg',
    birthdate: '2000-11-16 00:00:00',
    iconesigno: 'noto-v1:scorpio',
    chavePix: null,
    tipoChavePix: null,
    apelido: 'Vládia',
    sobrenome: 'Mori Pianca',
    instagram: 'vladianutri',
    images: null,
    picture_url: null,
  },
  {
    id: 30,
    nome: 'Izadora',
    foto: '/fotos/Izadora.jpg\n',
    birthdate: '2000-07-28 00:00:00',
    iconesigno: 'noto-v1:leo',
    chavePix: null,
    tipoChavePix: null,
    apelido: 'Iza',
    sobrenome: '',
    instagram: 'izavivian',
    images: null,
    picture_url: null,
  },
  {
    id: 7,
    nome: 'Ana Carolina ',
    foto: '/fotos/Aninha.png',
    birthdate: '1976-08-09 00:00:00',
    iconesigno: 'noto-v1:leo',
    chavePix: '11060647800',
    tipoChavePix: 'cpf',
    apelido: 'Aninha',
    sobrenome: 'A. Munhoz Mori',
    instagram: 'ac_munhozmori',
    images: '9a0447ed-85c8-4d88-af8f-c7cc1199b84f',
    picture_url: null,
  },
  {
    id: 8,
    nome: 'Letícia',
    foto: '/fotos/Leticia.jpg',
    birthdate: '2000-08-24 00:00:00',
    iconesigno: 'noto-v1:virgo',
    chavePix: '96385274155',
    tipoChavePix: 'cpf',
    apelido: null,
    sobrenome: ' Gonçalves Batista',
    instagram: 'leticiagbatista',
    images: '5565de45-2eb6-44fe-a49d-1aa06bd29a5a',
    picture_url: null,
  },
  {
    id: 9,
    nome: 'Vanessa',
    foto: '/fotos/Vanessa.jpg',
    birthdate: '2000-09-07 00:00:00',
    iconesigno: 'noto-v1:virgo',
    chavePix: '27423754811',
    tipoChavePix: 'cpf',
    apelido: null,
    sobrenome: ' Ambrosio Rebouças e Paula Lima',
    instagram: 'van_reboucas',
    images: '7bea2d40-10d8-422f-8475-353b76373643',
    picture_url: null,
  },
  {
    id: 10,
    nome: 'Carolina',
    foto: '/fotos/CarolMori.jpg',
    birthdate: '2000-09-26 00:00:00',
    iconesigno: 'noto-v1:libra',
    chavePix: '14997402449',
    tipoChavePix: 'celular',
    apelido: 'Carol Mori',
    sobrenome: ' Mori Mendonça',
    instagram: 'moricarol',
    images: 'aa377107-0fdc-427c-beaf-81498e8fc887',
    picture_url: null,
  },
  {
    id: 5,
    nome: 'Andrea ',
    foto: '/fotos/Deia.jpg',
    birthdate: '2000-05-15 00:00:00',
    iconesigno: 'noto-v1:taurus',
    chavePix: '27631283869',
    tipoChavePix: 'cpf',
    apelido: 'Deia',
    sobrenome: 'Luzia Morales Pontes',
    instagram: 'deia_morales',
    images: 'b5a0b900-8db9-4c35-85e0-3c49a54696ad',
    picture_url: null,
  },
  {
    id: 11,
    nome: 'Cristiane ',
    foto: '/fotos/Nani.jpg',
    birthdate: '2000-10-26 00:00:00',
    iconesigno: 'noto-v1:scorpio',
    chavePix: 'nanicrivelli@uol.com.br',
    tipoChavePix: 'email',
    apelido: 'Nani',
    sobrenome: 'Crivelli Carvalho',
    instagram: 'nacasadanani',
    images: '04fe456c-ed1f-41cb-ad0f-63868e0b0ccc',
    picture_url: null,
  },
  {
    id: 14,
    nome: 'Cássia ',
    foto: '/fotos/Cassia.jpg',
    birthdate: '2000-12-11 00:00:00',
    iconesigno: 'noto-v1:sagittarius',
    chavePix: '15832509803',
    tipoChavePix: 'cpf',
    apelido: null,
    sobrenome: 'de Paiva Vieira Andrade',
    instagram: 'cassiavieiraandrade',
    images: '2041880b-ce38-4532-bb8a-cf62de691f19',
    picture_url: null,
  },
  {
    id: 33,
    nome: 'Viviane',
    foto: '/fotos/Vivi.jpg\r\n',
    birthdate: '1980-09-30 00:00:00',
    iconesigno: 'noto-v1:libra',
    chavePix: null,
    tipoChavePix: null,
    apelido: 'Vivi',
    sobrenome: 'Silvestre Cortez',
    instagram: 'vivisilvestrecortez',
    images: null,
    picture_url: null,
  },
  {
    id: 1,
    nome: 'Deborah \r\n',
    foto: '/fotos/Deborah.jpg',
    birthdate: '2000-01-10 00:00:00',
    iconesigno: 'noto-v1:capricorn',
    chavePix: '',
    tipoChavePix: null,
    apelido: null,
    sobrenome: 'Cristina de Carvalho',
    instagram: 'deborahcarvalho181',
    images: null,
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/1-Deborah.jpg',
  },
  {
    id: 13,
    nome: 'Aline ',
    foto: '/fotos/Aline.jpg',
    birthdate: '2000-11-27 00:00:00',
    iconesigno: 'noto-v1:sagittarius',
    chavePix: '14996119998',
    tipoChavePix: 'celular',
    apelido: null,
    sobrenome: 'Aparecida Ribeiro Munho',
    instagram: 'alinneribeirosemijoias',
    images: '9029a633-6ce5-4cec-baef-337d37218f37',
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/13-Aline.jpg',
  },
  {
    id: 2,
    nome: 'Ana Paula ',
    foto: '/fotos/AnaPaulaMaita.jpg',
    birthdate: '2000-01-18 00:00:00',
    iconesigno: 'noto-v1:capricorn',
    chavePix: '',
    tipoChavePix: null,
    apelido: null,
    sobrenome: 'da Cunha Maita',
    instagram: 'anapaulamaita',
    images: '19756e9a-ce3d-4c21-8f31-5b19ea66bc7a',
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/2-AnaPaulaMaita.jpg',
  },
  {
    id: 12,
    nome: 'Camila ',
    foto: '/fotos/Camila.jpg',
    birthdate: '1984-11-15 00:00:00',
    iconesigno: 'noto-v1:scorpio',
    chavePix: '14997093599',
    tipoChavePix: 'celular',
    apelido: null,
    sobrenome: 'Paulino Gatti',
    instagram: 'camilapgatti',
    images: 'dfbaa1b3-b5f2-4d34-95ba-2357bd73168a',
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/12-Camila.jpg',
  },
  {
    id: 3,
    nome: 'Stella ',
    foto: '/fotos/Stella.jpg',
    birthdate: '2000-04-04 00:00:00',
    iconesigno: 'noto-v1:aries',
    chavePix: '',
    tipoChavePix: null,
    apelido: null,
    sobrenome: 'Racy Barbi Ronqui',
    instagram: 'stellabr',
    images: 'e563a56b-12f8-47eb-8ae4-89f9aa85773f',
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/3-Stella.jpg',
  },
];
