import { Person } from './types';

export const lulus = [
  {
    id: 4,
    fullName: 'Sueli Corrêa de Oliveira',
    instagram: 'suelli_correaa',
    images: null,
    picture_url: null,
  },
  {
    id: 6,
    fullName: 'Carolina Maita',
    instagram: 'carolmaita',
    images: '9a56cefc-cfc3-4c8c-ab76-f3bff0286715',
    picture_url: null,
  },
  {
    id: 29,
    fullName: 'Não Participa da Vaquinha',
    instagram: null,
    images: null,
    picture_url: null,
  },
  {
    id: 27,
    fullName: 'Vládia MariaMori Pianca',
    instagram: 'vladianutri',
    images: null,
    picture_url: null,
  },
  {
    id: 30,
    fullName: 'Izadora',
    instagram: 'izavivian',
    images: null,
    picture_url: null,
  },
  {
    id: 7,
    fullName: 'Ana Carolina A. Munhoz Mori',
    instagram: 'ac_munhozmori',
    images: '9a0447ed-85c8-4d88-af8f-c7cc1199b84f',
    picture_url: null,
  },
  {
    id: 8,
    fullName: 'Letícia Gonçalves Batista',
    instagram: 'leticiagbatista',
    images: '5565de45-2eb6-44fe-a49d-1aa06bd29a5a',
    picture_url: null,
  },
  {
    id: 9,
    fullName: 'Vanessa Ambrosio Rebouças e Paula Lima',
    instagram: 'van_reboucas',
    images: '7bea2d40-10d8-422f-8475-353b76373643',
    picture_url: null,
  },
  {
    id: 10,
    fullName: 'Carolina Mori Mendonça',
    instagram: 'moricarol',
    images: 'aa377107-0fdc-427c-beaf-81498e8fc887',
    picture_url: null,
  },
  {
    id: 5,
    fullName: 'Andrea Luzia Morales Pontes',
    instagram: 'deia_morales',
    images: 'b5a0b900-8db9-4c35-85e0-3c49a54696ad',
    picture_url: null,
  },
  {
    id: 11,
    fullName: 'Cristiane Crivelli Carvalho',
    instagram: 'nacasadanani',
    images: '04fe456c-ed1f-41cb-ad0f-63868e0b0ccc',
    picture_url: null,
  },
  {
    id: 14,
    fullName: 'Cássia de Paiva Vieira Andrade',
    instagram: 'cassiavieiraandrade',
    images: '2041880b-ce38-4532-bb8a-cf62de691f19',
    picture_url: null,
  },
  {
    id: 33,
    fullName: 'VivianeSilvestre Cortez',
    instagram: 'vivisilvestrecortez',
    images: null,
    picture_url: null,
  },
  {
    id: 1,
    fullName: 'Deborah \r\nCristina de Carvalho',
    instagram: 'deborahcarvalho181',
    images: null,
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/1-Deborah.jpg',
  },
  {
    id: 13,
    fullName: 'Aline Aparecida Ribeiro Munho',
    instagram: 'alinneribeirosemijoias',
    images: '9029a633-6ce5-4cec-baef-337d37218f37',
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/13-Aline.jpg',
  },
  {
    id: 2,
    fullName: 'Ana Paula da Cunha Maita',
    instagram: 'anapaulamaita',
    images: '19756e9a-ce3d-4c21-8f31-5b19ea66bc7a',
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/2-AnaPaulaMaita.jpg',
  },
  {
    id: 12,
    fullName: 'Camila Paulino Gatti',
    instagram: 'camilapgatti',
    images: 'dfbaa1b3-b5f2-4d34-95ba-2357bd73168a',
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/12-Camila.jpg',
  },
  {
    id: 3,
    fullName: 'Stella Racy Barbi Ronqui',
    instagram: 'stellabr',
    images: 'e563a56b-12f8-47eb-8ae4-89f9aa85773f',
    picture_url:
      'https://vttyctdmifvabhlvcmzd.supabase.co/storage/v1/object/public/profile_pictures/profile_pictures/3-Stella.jpg',
  },
];

export const participants: Person[] = [
  {
    id: 1,
    name: 'Deborah',
    date: new Date('1980-01-10'),
    month: '01',
    phone: '14997551900',
    picture: '/fotos/Deborah.jpg',
    instagram: 'deborahcarvalho181',
    pix_key: '14997551900',
    pix_key_type: 'phone',
    fullName: 'Deborah Cristina de Carvalho',
    city: 'OURINHOS',
  },
  {
    id: 2,
    name: 'Ana Paula',
    date: new Date('1980-01-18'),
    month: '01',
    picture: '/fotos/AnaPaulaMaita.jpg',
    instagram: 'anapaulamaita',
    pix_key: '',
    pix_key_type: 'none',
    phone: ' 14997418201',
    fullName: 'Ana Paula da Cunha Maita',
    city: 'OURINHOS',
  },
  {
    id: 3,
    name: 'Stella',
    date: new Date('1980-04-04'),
    month: '04',
    picture: '/fotos/Stella.jpg',
    instagram: 'stellarbr',
    pix_key: '34061032860',
    pix_key_type: 'cpf',
    phone: '14997107007',
    fullName: 'Stella Racy Barbi Ronqui',
    city: 'OURINHOS',
  },
  {
    id: 4,
    name: 'Sueli',
    date: new Date('1980-04-09'),
    month: '04',
    picture: '/fotos/Sueli.jpg',
    instagram: 'suelli_correaa',
    pix_key: '1899645075',
    pix_key_type: 'phone',
    phone: '1899645075',
    fullName: 'Sueli Corrêa de Oliveira',
    city: 'OURINHOS',
  },
  {
    id: 5,
    name: 'Deia',
    date: new Date('1980-05-15'),
    month: '05',
    picture: '/fotos/Deia.jpg',
    instagram: 'deia_morales',
    pix_key: '27631283869',
    pix_key_type: 'cpf',
    phone: '11974644729',
    fullName: 'Andrea Luzia Morales Pontes',
    city: 'SAO PAULO',
  },
  {
    id: 6,
    name: 'Carol Maita',
    date: new Date('1980-05-28'),
    month: '05',
    picture: '/fotos/CarolMaita.jpg',
    instagram: 'carolmaita',
    pix_key: '28375340804',
    pix_key_type: 'cpf',
    phone: '11971514607',
    fullName: 'Cristiane Crivelli Carvalho',
    city: 'SAO PAULO',
  },
  {
    id: 7,
    name: 'Josy',
    date: new Date('1980-07-15'),
    month: '07',
    picture: '/fotos/Josy.jpg',
    instagram: '',
    pix_key: 'josybernardo@yahoo.com.br',
    pix_key_type: 'email',
    phone: '14998731381',
    fullName: 'Josy Mesquita Bernardo Bilar',
    city: 'OURINHOS',
  },
  {
    id: 8,
    name: 'Aninha',
    date: new Date('1980-08-09'),
    month: '08',
    picture: '/fotos/Aninha.png',
    instagram: 'ac_munhozmori',
    pix_key: '11060647800',
    pix_key_type: 'cpf',
    phone: '14981169234',
    fullName: 'Ana Carolina A. Munhoz Mori',
    city: 'OURINHOS',
  },
  {
    id: 9,
    name: 'Letícia',
    date: new Date('1980-08-24'),
    month: '08',
    picture: '/fotos/Leticia.jpg',
    instagram: 'leticiagbatista',
    pix_key: '96385274155',
    pix_key_type: 'cpf',
    phone: '14997738588',
    fullName: 'Letícia Gonçalves Batista',
    city: 'OURINHOS',
  },
  {
    id: 10,
    name: 'Sylvia',
    date: new Date('1980-09-03'),
    month: '09',
    picture: '/fotos/Sylvia.jpg',
    instagram: 'yarasylvia',
    pix_key: '',
    pix_key_type: 'none',
    phone: '14998250476',
    fullName: 'Sylvia Yara Cintra Mattar',
    city: 'OURINHOS',
  },
  {
    id: 11,
    name: 'Vanessa',
    date: new Date('1980-09-07'),
    month: '09',
    picture: '/fotos/Vanessa.jpg',
    instagram: 'van_reboucas',
    pix_key: '27423754811',
    pix_key_type: 'cpf',
    phone: '11994919832',
    fullName: 'Vanessa Ambrosio Rebouças e Paula Lima',
    city: 'OURINHOS',
  },
  {
    id: 12,
    name: 'Carol Mori',
    date: new Date('1980-09-26'),
    month: '09',
    picture: '/fotos/CarolMori.jpg',
    instagram: 'moricarol',
    pix_key: '14997402449',
    pix_key_type: 'phone',
    phone: '14997402449',
    fullName: 'Carolina Mori Mendonça',
    city: 'OURINHOS',
  },
  {
    id: 13,
    name: 'Vivi',
    date: new Date('1980-09-30'),
    month: '09',
    picture: '/fotos/Vivi.jpg',
    instagram: 'vivisilvestrecortez',
    pix_key: 'Viviane',
    pix_key_type: 'cpf',
    phone: '14996896707',
    fullName: 'Viviane Silva Cortez',
    city: 'OURINHOS',
  },
  {
    id: 14,
    name: 'Nani',
    date: new Date('1980-10-26'),
    month: '10',
    picture: '/fotos/Nani.jpg',
    instagram: 'nacasadanani',
    pix_key: 'nanicrivelli@uol.com.br',
    pix_key_type: 'email',
    phone: '14981647980',
    fullName: 'Cristiane Crivelli Carvalho',
    city: 'OURINHOS',
  },
  {
    id: 15,
    name: 'Camila',
    date: new Date('1980-11-15'),
    month: '11',
    picture: '/fotos/Camila.jpg',
    instagram: 'camilapgatti',
    pix_key: '',
    pix_key_type: 'none',
    phone: '14997093599',
    fullName: 'Camila Paulino Gatti',
    city: 'OURINHOS',
  },
  {
    id: 16,
    name: 'Vládia',
    date: new Date('1980-11-16'),
    month: '11',
    picture: '/fotos/Vladia.jpg',
    instagram: 'vladianutri',
    pix_key: '19536701804',
    pix_key_type: 'cpf',
    phone: '14991721673',
    fullName: 'Vládia Maria Mori Pianca',
    city: 'OURINHOS',
  },
  {
    id: 17,
    name: 'Aline',
    date: new Date('1980-11-27'),
    month: '11',
    picture: '/fotos/Aline.jpg',
    instagram: 'alinneribeirosemijoias',
    pix_key: '14996119998',
    pix_key_type: 'phone',
    phone: '14996119998',
    fullName: 'Aline Aparecida Ribeiro Munhoz',
    city: 'OURINHOS',
  },
  {
    id: 18,
    name: 'Cássia',
    date: new Date('1980-12-11'),
    month: '12',
    picture: '/fotos/Cassia.jpg',
    instagram: 'cassiavieiraandrade',
    pix_key: '15832509803',
    pix_key_type: 'cpf',
    phone: '14 996060175',
    fullName: 'Cássia de Paiva Vieira Andrade',
    city: 'OURINHOS',
  },
];
